version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: project_dev_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: maulanayusup701/phpmyadmindarkmode:5.2.1
    container_name: project_dev_phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
      PHPMYADMIN_THEME: blueberry
    ports:
      - "8081:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
